### ISSUE TITLE
what are the goals of this profile?

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#26]
https://github.com/IHE/ITI.IUA/blob/master/IHE_ITI_Suppl_IUA.md#introduction-to-this-supplement

When reading through this profile, I jotted down my interpretation of the goals of the profile. They are:
* Enable disparate RS and AS to work together.
* Defines a format for tokens as JWTs
* Enables SAML tokens to be used in OAuth2
* Defines a token introspection endpoint
* Optionally supports the Device Authorization OAuth2 extension (RFC 8628)
* Requires servers to support PKCE
* Support POU and BPPC (consent) access token JWT extensions

The problem statement and problem background of the profile make it sound like the primary goal is patient-facing apps using the auth code flow, but the majority of the features introduced by this profile above and beyond SMART don't obviously accomplish patient access, but rather accommodate more complex data/environment architectures. 

I'm largely unfamiliar with the format of IHE profiles, I apologize, would it be reasonable to define the goals of the profile in the profile?

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by msmock** [comment]
@isaacvetter 

Maybe not the answer to your question, but to give you some background why I engaged in IUA: 

When working on the specification of how to enable mobile access for patients and healthcare professionals for the Swiss electronic health record, SMART on FHIR was our first choice. But when trying to apply it to our environment we faced serious problems to apply it. 

First, while SMART on FHIR works fine for fully modularized applications with independent views (which is the scope of SMART) we realized that SMART on FHIR produces a lot of overhead, since you need to run the launch sequence for each view, if they have a different scope. Second, SMART on FHIR currently does not specify how to convey information required for the policy enforcement on the resource server side. Obviously, in SMART on FHIR one can extend the token with the required information and we did this, by merging the SMART on FHIR definitions with the one from IUA. But SMART on FHIR alone does not work for us, thus we need IUA.   

I'm very interested in an exchange on this topic, since the specification to apply SMART on FHIR and IUA to the Swiss EPR is not finalized yet. Maybe we can reserve a slot for you to present your solution and discuss it in our bi-weekly IUA meeting.

**Comment by joostreuzel** [comment]
My two cents: Philips as a solution provider must deploy systems in rather heterogeneous environments. Many of the systems that we need to integrate have their own history, and may come with their own user management (at best synchronized through a hospital's AD system), permission models, data storage, deployment models, etc. 

To enable these systems to participate in a (distributed) workflow there is a need for an (RESTful) API-based integration. In most cases we use FHIR, utilizing the IHE profiles where possible, but other APIs must be supported as well. To make the API-based integrations work, consensus must exist on the authorization model. This is where IUA comes in for us.

SMART-on-FHIR does not always work for us.  SMART assumes a central repository (the EHR) with a strongly associated authorization server. Clients are assumed to center around that central repository. We found that model too simplistic. As said, many different systems have their own history and may come with their own user management, permission models, data storage, etc. Data and functionality is inherently distributed across these systems. This means that a search for patient data is often a distributed search: it has to be pulled from several repositories. Workflow tasks are not just directed toward that single repository, but need to target different applications. 

Utilizing SMART-launch for these integrations would imply that such sequences would need to be executed between each pair of interacting systems. Moreover, as different systems would have their own user and permission models, they would need to act as their own authorization server. This is too complicated to add to most of these (legacy) systems.

Instead we are looking more to service-2-service style of integrations, allowing _trusted_ systems to exchange data and tasks amongst each other, keeping a bit away from user-centric controls and permission models (which are assumed to be managed by participating systems). At best we can indicate the active user (or even the patient that person is working on), but what that exactly implies is typically controlled by the participating systems. As such, the SMART for backend services lies much closer to what we can effectively do than the EMR-related flows.

**Comment by joostreuzel** [comment]
Summarizing: I see two major use-cases:
1. A front-end application, being mobile or web, in which a user (patient or professional) logs in and gets (limited) access to patient health data
1. A system integration in which participating systems, ranging from individual devices to large scale IT systems, need to exchange data and tasks, without mandatory user involvement.
