### ISSUE TITLE
Consider new IETF specifications

### ISSUE THREAD

**Issue by steinarnoem** [IHE/ITI.IUA#50]
3.71

The IETF OAuth Working group have been developing some new extensions to the OAuth framework that addresses some problem areas concerning the original protocol framework. There are several interesting and relevant specifications for IUA, but these two are of specific value to our domain: 
- https://tools.ietf.org/html/draft-ietf-oauth-par-05
- https://tools.ietf.org/html/draft-ietf-oauth-rar-03#page-31 

The "PAR" specification addresses size and security issues that occur when using URI parameters in authn & authz requests, and describes a more robust and secure way of doing it.

The "RAR" specification describes an interoperable way of specifying and passing fine-grained authorization requirements. For most cases the client system/app knows more about the users context than the AS or other external components and often needs to be treated as a "claims-provider" in authorization scenarios. The RAR specification contains examples of how we have utilized the structure in the health sector in Norway.

I think it would be wise of IHE to consider if these specification add value to the use cases for IUA. I know that both specifications have been implemented by several commercial products - which makes interoperability and adoption more feasible.

**Comment by msmock** [comment]
To be discussed: 
The par RFC looks like a port of the SAML 2.0 artifact resolve protocol for the OAuth authorization request. As explained in the RFC the security is increased only in scenarios where the scope claims contain sensitive data which should not be presented to the front channel, i.e. the browser. I don't see this as typical for application in the healthcare sector. Also, OAuth does not forbid to send the authorization request via the backchannel to hide it from a browser or other front channels. I suggest not to add this since the potential security gain is less the pain caused by the higher complexity.

To be discussed: 
We don't say much on scope claims and IUA as well as OAuth is open to add other parameter to the authorization request message. IUA does not block implementers from implementing the claims as suggested by the rar RFC.

**Comment by msmock** [comment]
@msmock Add open issue to IUA to follow up

**Comment by msmock** [comment]
Added as open issues to be watched by the TC as agreed upon in the last meeting: 

- **Issue 14**: The IETF OAuth Working group developed an extensions to the OAuth framework that specifies an option to convey more fine grained claims with the authorization request. The OAuth 2.0 Rich Authorization Requests (draft-ietf-oauth-rar-03) specification introduces a new parameter "authorization_details" in authorization requests that allows clients to specify fine-grained scope claims in a JSON data structure. IUA currently does not define scopes at all and therefore does not mandate the way to convey more fine-grained scope claims in authorization requests. The commitee will watch the acceptance and the development of the draft and future versions may rely on rich authorization requests.    

- **Issue 15**: The IETF OAuth Working group developed an extension to the OAuth framework that which increases the security in cases where the authorization request contains sensitive data which should not be presented to the user agent (browser). The OAuth 2.0 Pushed Authorization Requests (draft-ietf-oauth-par-05) specification provides an interoperable way for Authorization Clients to push the payload of an authorization request directly to the authorization server via the back-channel in exchange for a "request_uri" value which may be used by the user agent (front-channel) in a subsequent request to reference the authorization request. The technical commitee currently is no aware of a demand of vendors or users for option in healthcare applications. The commitee will watch the future demand and the development of the draft specification. Future versions of IUA may rely on pushed authorization requests.
